platform :ios, '7.1'
use_frameworks!

target 'Archery Score' do
  pod 'FMDB', '~> 2.2'
	#pod 'AFNetworking'
	pod 'SDWebImage', '~> 3.7.1'
	pod 'UIViewController+Swizzled', '~> 1.2'
	#pod 'PaymentKit', :git => 'https://github.com/stripe/PaymentKit.git'
	#pod 'Mantle'
	#pod 'MMDrawerController', '~> 0.5.6'
	#pod 'MYBlurIntroductionView', '~> 1.0.3'
	pod 'HTAutocompleteTextField', '~> 1.3.2'
	pod 'MJRefresh'
  pod 'YCXMenu'
	pod 'LTNavigationBar', '~> 2.0.3'
	pod 'FDFullscreenPopGesture', '1.1'
	pod 'DZNEmptyDataSet' 
	pod 'pop'
	pod 'TOWebViewController'
    #pod 'ContextMenu.iOS', '~> 1.1.0'
    #pod 'CYLTabBarController', '~> 1.0.5'
  pod 'UITableView+FDTemplateLayoutCell'
    #pod 'FLEX', :configurations => ['Debug']
  pod 'JPFPSStatus', '~> 0.0.2'
  pod 'TKRoundedView'
    #pod 'WMPageController'
  pod 'IQKeyboardManager'
    #pod 'MLeaksFinder'
    #pod 'XMLDictionary', '~> 1.4'
  pod 'DHSmartScreenshot'
pod 'InMobiSDK'
pod 'iCarousel'
#pod 'MWPhotoBrowser'
#pod 'PSTCollectionView'
#pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
#pod 'PNChart'
end
